services:
  postgres:
    image: postgres:17
    container_name: issue-tracker-postgres

    environment:
      POSTGRES_DB: issue_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.7
    container_name: issue-tracker-keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import

volumes:
  postgres_data: