### Create task
POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "title": "Implement UpdateTask audit",
  "description": "Implement UpdateTask audit",
  "assigneeId": null,
  "priority": "HIGH"
}

### Get task
GET http://localhost:8080/api/tasks/6a173437-23e2-466e-815f-3ed1a9298066
Authorization: Bearer {{access_token}}

### Browse tasks

POST http://localhost:8080/api/tasks/browse
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "priority": [
    "HIGH"
  ]
}

### Browse audit logs
POST http://localhost:8080/api/audit/browse
Content-Type: application/json
Authorization: Bearer {{access_token}}

{}

### Browse audit logs - filter by action
POST http://localhost:8080/api/audit/browse
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "action": "TASK_CREATED"
}

### Task patch test

PATCH http://localhost:8080/api/tasks/f0a8779c-edf1-48c2-94b8-884ab92806df
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "assigneeId": "38aedc70-d562-4148-90be-a2fae8684eca",
  "status": "IN_PROGRESS"
}