spring:
  application:
    name: issue-tracker-jooq

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/issue_tracker
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jooq:
    sql-dialect: postgres

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/issue-tracker