package cz.developerthomas.issuetrackerjooq.core.identityprovider.keycloak

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(KeycloakProperties::class)
class KeycloakConfiguration